### ISSUE TITLE
No module named 'colorama' after installing with pip

### ISSUE THREAD

**Issue by m-aciek** [sarugaku/vistir#45]
Hi, I encountered such error with vistir-0.2.5 (and passa 0.3.0). Hope it's right place to report that.

```sh
(.virtualenv) …@…:/…$ python -m passa lock
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/carflow/.virtualenv/lib/python3.6/site-packages/passa/__main__.py", line 6, in <module>
    main()
  File "/srv/carflow/.virtualenv/lib/python3.6/site-packages/passa/cli/__init__.py", line 30, in main
    module = importlib.import_module(name, __name__)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/…/.virtualenv/lib/python3.6/site-packages/passa/cli/freeze.py", line 11, in <module>
    import vistir.misc
  File "/…/.virtualenv/lib/python3.6/site-packages/vistir/__init__.py", line 31, in <module>
    from .spin import VistirSpinner, create_spinner
  File "/…/.virtualenv/lib/python3.6/site-packages/vistir/spin.py", line 10, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
```

**Comment by techalchemy** [comment]
Hmm yes, I think you need `vistir[spinner]` (blame @uranusjr because he made me not include the spinner by default)

sorry for the confusion!
